[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/docker-entrypoint.sh"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
